#!/usr/bin/env python3
from gi.repository import WebKit
from gi.repository import Gtk
from sys import argv

view = WebKit.WebView()

sw = Gtk.ScrolledWindow()
sw.add(view)
sw.set_size_request(500,305)

win = Gtk.Window(Gtk.WindowType.TOPLEVEL)
win.add(sw)
win.show_all()
if len(argv) > 1:
	view.open(argv[1])
else:
	view.open("http://google.com/")
Gtk.main()
