#!/usr/bin/env python3
from gi.repository import WebKit
from gi.repository import Gtk
from argparse import ArgumentParser
parser = ArgumentParser()
parser.add_argument("-s", "--site", dest="site",
help="site", metavar="SITE")
args = parser.parse_args()

view = WebKit.WebView() 

sw = Gtk.ScrolledWindow() 
sw.add(view) 
sw.set_size_request(500,305)

win = Gtk.Window(Gtk.WindowType.TOPLEVEL) 
win.add(sw) 
win.show_all()
view.open("http://google.com/") 
if args.site:
	view.open(args.site)
Gtk.main()
